print ("    ____________________    ________             ")
print ("    |                  |    | DELL |         ")
print ("    | Python  3.5      |    | : :  |         ")
print ("    | IDLE             |    | . .  |              ")
print ("    | Hello World      |    | O O  |              ")
print ("    |                  |    | = =  |              ")
print ("    |                  |----| = =  |                  ")
print ("    --------------------    --------                  ")
print ("        |    |     ")
print ("        |    |      ")
print ("        |  -----        ")
print ("    ____________    ")
print ("    |qwertyuiop|     ") 
print ("    |asdfghjkl;|----------        ")
print ("    |zxcvbnm,.?|         |")
print ("    ------------         |")
print ("                        (')")
print (" ")
print (" ")
